# Generated by Django 4.0.6 on 2022-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='asm/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
