# Generated by Django 4.0.6 on 2022-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='asm/images'),
        ),
    ]
