# Generated by Django 4.0.6 on 2022-07-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0004_contact_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
    ]
